### ISSUE TITLE
Document where or how create this image stephaneklein/restic-backup-docker:1.2-0.9.4

### ISSUE THREAD

**Issue by stephane-klein** [stephane-klein/restic-pg_dump-docker#1]
Document where or how create this image [`stephaneklein/restic-backup-docker:1.2-0.9.4`](https://github.com/stephane-klein/restic-pg_dump-docker/blob/f18f28ab4ccdb3e998eadf423f4964f63584dc4f/Dockerfile#L3)

cc @Its-Alex

**Comment by Its-Alex** [comment]
@stephane-klein Since this commit https://github.com/stephane-klein/restic-pg_dump-docker/commit/7d2e4fe11909fdceede38bbfe5ee1b31928f8001 I think we can close this issue
